In [11]:
import pandas as pd
import sqlite3
conn = sqlite3.connect('assignment.db')
print("SQL Setup Ready!")

SQL Setup Ready!

Worker Table Analysis

In [14]:

worker_setup = """
DROP TABLE IF EXISTS Worker;

CREATE TABLE Worker (
    WORKER_ID INT,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    SALARY INT,
    JOINING_DATE TEXT,
    DEPARTMENT TEXT
);

INSERT INTO Worker VALUES (1, 'Monika', 'Arora', 100000, '2014-02-20', 'HR');
INSERT INTO Worker VALUES (2, 'Niharika', 'Verma', 80000, '2014-06-11', 'Admin');
INSERT INTO Worker VALUES (3, 'Vishal', 'Singhal', 300000, '2014-02-20', 'HR');
INSERT INTO Worker VALUES (4, 'Amitabh', 'Singh', 500000, '2014-02-20', 'Admin');
INSERT INTO Worker VALUES (5, 'Vivek', 'Bhati', 500000, '2014-06-11', 'Admin');
INSERT INTO Worker VALUES (6, 'Vipul', 'Diwan', 200000, '2014-06-11', 'Account');
INSERT INTO Worker VALUES (7, 'Satish', 'Kumar', 75000, '2014-01-20', 'Account');
INSERT INTO Worker VALUES (8, 'Geetika', 'Chauhan', 90000, '2014-04-11', 'Admin');
"""
conn.executescript(worker_setup)
print("Worker Table is Ready with Data!")

Worker Table is Ready with Data!

In [15]:
query1 = "SELECT * FROM Worker ORDER BY FIRST_NAME ASC, DEPARTMENT DESC"
pd.read_sql_query(query1, conn)

   WORKER_ID FIRST_NAME LAST_NAME  SALARY JOINING_DATE DEPARTMENT
0          4    Amitabh     Singh  500000   2014-02-20      Admin
1          8    Geetika   Chauhan   90000   2014-04-11      Admin
2          1     Monika     Arora  100000   2014-02-20         HR
3          2   Niharika     Verma   80000   2014-06-11      Admin
4          7     Satish     Kumar   75000   2014-01-20    Account
5          6      Vipul     Diwan  200000   2014-06-11    Account
6          3     Vishal   Singhal  300000   2014-02-20         HR
7          5      Vivek     Bhati  500000   2014-06-11      Admin

In [16]:
query2 = "SELECT * FROM Worker WHERE FIRST_NAME IN ('Vipul', 'Satish')"
pd.read_sql_query(query2, conn)

   WORKER_ID FIRST_NAME LAST_NAME  SALARY JOINING_DATE DEPARTMENT
0          6      Vipul     Diwan  200000   2014-06-11    Account
1          7     Satish     Kumar   75000   2014-01-20    Account

In [17]:
query3 = "SELECT * FROM Worker WHERE FIRST_NAME LIKE '_____h'"
pd.read_sql_query(query3, conn)

   WORKER_ID FIRST_NAME LAST_NAME  SALARY JOINING_DATE DEPARTMENT
0          7     Satish     Kumar   75000   2014-01-20    Account

In [24]:
query4 = "SELECT * FROM Worker WHERE SALARY BETWEEN 100000 AND 500000"
pd.read_sql_query(query4, conn)

   WORKER_ID FIRST_NAME LAST_NAME  SALARY JOINING_DATE DEPARTMENT
0          1     Monika     Arora  100000   2014-02-20         HR
1          3     Vishal   Singhal  300000   2014-02-20         HR
2          4    Amitabh     Singh  500000   2014-02-20      Admin
3          5      Vivek     Bhati  500000   2014-06-11      Admin
4          6      Vipul     Diwan  200000   2014-06-11    Account

In [19]:
query5 = "SELECT FIRST_NAME, LAST_NAME, DEPARTMENT, COUNT(*) FROM Worker GROUP BY FIRST_NAME, LAST_NAME, DEPARTMENT HAVING COUNT(*) > 1"
pd.read_sql_query(query5, conn)

Empty DataFrame
Columns: [FIRST_NAME, LAST_NAME, DEPARTMENT, COUNT(*)]
Index: []

In [20]:
query6 = "SELECT * FROM Worker LIMIT 6"
pd.read_sql_query(query6, conn)

   WORKER_ID FIRST_NAME LAST_NAME  SALARY JOINING_DATE DEPARTMENT
0          1     Monika     Arora  100000   2014-02-20         HR
1          2   Niharika     Verma   80000   2014-06-11      Admin
2          3     Vishal   Singhal  300000   2014-02-20         HR
3          4    Amitabh     Singh  500000   2014-02-20      Admin
4          5      Vivek     Bhati  500000   2014-06-11      Admin
5          6      Vipul     Diwan  200000   2014-06-11    Account

In [21]:
query7 = "SELECT DEPARTMENT FROM Worker GROUP BY DEPARTMENT HAVING COUNT(*) < 5"
pd.read_sql_query(query7, conn)

  DEPARTMENT
0    Account
1      Admin
2         HR

In [22]:
query8 = "SELECT DEPARTMENT, COUNT(*) AS Total_Workers FROM Worker GROUP BY DEPARTMENT"
pd.read_sql_query(query8, conn)

  DEPARTMENT  Total_Workers
0    Account              2
1      Admin              4
2         HR              2

In [23]:
query9 = "SELECT FIRST_NAME, DEPARTMENT, MAX(SALARY) FROM Worker GROUP BY DEPARTMENT"
pd.read_sql_query(query9, conn)

  FIRST_NAME DEPARTMENT  MAX(SALARY)
0      Vipul    Account       200000
1    Amitabh      Admin       500000
2     Vishal         HR       300000

Student Table Analysis

In [27]:
# Yeh code purani error ko khatam kar dega
import pandas as pd
import sqlite3

# Connection check
conn = sqlite3.connect('assignment.db')

student_setup = """
DROP TABLE IF EXISTS student;

CREATE TABLE student (
    StdID INT PRIMARY KEY,
    StdName TEXT,
    Sex TEXT,
    Percentage INT,
    Class TEXT,
    Sec TEXT,
    Stream TEXT,
    DOB TEXT
);

INSERT INTO student VALUES
(1001, 'Surekha Joshi', 'Female', 82, '12', 'A', 'Science', '3/8/1998'),
(1002, 'MAAHI AGARWAL', 'Female', 56, '11', 'C', 'Commerce', '11/23/2008'),
(1003, 'Sanam Verma', 'Male', 59, '11', 'C', 'Commerce', '6/29/2006'),
(1004, 'Ronit Kumar', 'Male', 63, '11', 'C', 'Commerce', '11/5/1997'),
(1005, 'Dipesh Pulkit', 'Male', 78, '11', 'B', 'Science', '14/09/2003');
"""
conn.executescript(student_setup)
print("Student Table is Ready!")

Student Table is Ready!

In [29]:
pd.read_sql_query("SELECT * FROM student", conn)

   StdID        StdName     Sex  Percentage Class Sec    Stream         DOB
0   1001  Surekha Joshi  Female          82    12   A   Science    3/8/1998
1   1002  MAAHI AGARWAL  Female          56    11   C  Commerce  11/23/2008
2   1003    Sanam Verma    Male          59    11   C  Commerce   6/29/2006
3   1004    Ronit Kumar    Male          63    11   C  Commerce   11/5/1997
4   1005  Dipesh Pulkit    Male          78    11   B   Science  14/09/2003

In [30]:
pd.read_sql_query("SELECT StdName, DOB FROM student", conn)

         StdName         DOB
0  Surekha Joshi    3/8/1998
1  MAAHI AGARWAL  11/23/2008
2    Sanam Verma   6/29/2006
3    Ronit Kumar   11/5/1997
4  Dipesh Pulkit  14/09/2003

In [31]:
pd.read_sql_query("SELECT * FROM student WHERE Percentage >= 80", conn)

   StdID        StdName     Sex  Percentage Class Sec   Stream       DOB
0   1001  Surekha Joshi  Female          82    12   A  Science  3/8/1998

In [32]:
pd.read_sql_query("SELECT StdName, Stream, Percentage FROM student WHERE Percentage > 80", conn)

         StdName   Stream  Percentage
0  Surekha Joshi  Science          82

In [33]:
pd.read_sql_query("SELECT * FROM student WHERE Stream = 'Science' AND Percentage > 75", conn)

   StdID        StdName     Sex  Percentage Class Sec   Stream         DOB
0   1001  Surekha Joshi  Female          82    12   A  Science    3/8/1998
1   1005  Dipesh Pulkit    Male          78    11   B  Science  14/09/2003